server:
  port: 15000
  ssl:
    key-store: keys/server.keystore
    key-store-type: JKS
    key-alias: tomcat
    enabled: true
    key-store-password: liyudong
    key-password: liyudong
#  keytool -export -alias tomcat -keystore server.keystore -rfc -file liyd_cas.crt